### ISSUE TITLE
Fails to patch

### ISSUE THREAD

**Issue by matejdro** [Irdroid/Irtoy_Irdroid_Patch#2]
Applying patch seems to fail on latest Lirc revision (`fc67ec65075bd9309ab78ea7ced98143e2bd7889`):

```
patching file irtoy.c
Hunk #1 succeeded at 50 with fuzz 1.
Hunk #2 FAILED at 386.
Hunk #3 FAILED at 394.
Hunk #4 FAILED at 422.
3 out of 4 hunks FAILED -- saving rejects to file irtoy.c.rej
```

**Comment by Irdroid** [comment]
Are you using irtoy.c from lirc 0.10.1?

**Comment by matejdro** [comment]
I'm just using ` git clone git://git.code.sf.net/p/lirc/git lirc`, which downloads latest git version (at `fc67ec65075bd9309ab78ea7ced98143e2bd7889`). How do I check which lirc version is that?

**Comment by Irdroid** [comment]
Did you used the patch from this link?

https://raw.githubusercontent.com/Irdroid/Irtoy_Irdroid_Patch/main/Irtoy_Irdroid_Lirc_Stability.patch

or from this one:

https://gist.githubusercontent.com/Irdroid/df859ae9b7cddd8fccde879804e056da/raw/c6664b43fd493371d8f89d515f40a99c3fc69d3c/Irtoy_Irdroid_Lirc_Stability.patch

**Comment by matejdro** [comment]
Later one (I was following instructions from the README).

**Comment by Irdroid** [comment]
okay, please try the first one and let me know

**Comment by matejdro** [comment]
First one worked. I guess you should update the readme?

Thanks
